/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ReportRouteImport } from './routes/report'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelectionsIndexRouteImport } from './routes/selections.index'
import { Route as ContactsIndexRouteImport } from './routes/contacts.index'
import { Route as SelectionsDateRouteImport } from './routes/selections.$date'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'

const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionsIndexRoute = SelectionsIndexRouteImport.update({
  id: '/selections/',
  path: '/selections/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectionsDateRoute = SelectionsDateRouteImport.update({
  id: '/selections/$date',
  path: '/selections/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/runs': typeof RunsRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/selections/$date': typeof SelectionsDateRoute
  '/contacts/': typeof ContactsIndexRoute
  '/selections/': typeof SelectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/runs': typeof RunsRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/selections/$date': typeof SelectionsDateRoute
  '/contacts': typeof ContactsIndexRoute
  '/selections': typeof SelectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/runs': typeof RunsRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/selections/$date': typeof SelectionsDateRoute
  '/contacts/': typeof ContactsIndexRoute
  '/selections/': typeof SelectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report'
    | '/runs'
    | '/contacts/$id'
    | '/selections/$date'
    | '/contacts/'
    | '/selections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report'
    | '/runs'
    | '/contacts/$id'
    | '/selections/$date'
    | '/contacts'
    | '/selections'
  id:
    | '__root__'
    | '/'
    | '/report'
    | '/runs'
    | '/contacts/$id'
    | '/selections/$date'
    | '/contacts/'
    | '/selections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportRoute: typeof ReportRoute
  RunsRoute: typeof RunsRoute
  ContactsIdRoute: typeof ContactsIdRoute
  SelectionsDateRoute: typeof SelectionsDateRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  SelectionsIndexRoute: typeof SelectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selections/': {
      id: '/selections/'
      path: '/selections'
      fullPath: '/selections/'
      preLoaderRoute: typeof SelectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selections/$date': {
      id: '/selections/$date'
      path: '/selections/$date'
      fullPath: '/selections/$date'
      preLoaderRoute: typeof SelectionsDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportRoute: ReportRoute,
  RunsRoute: RunsRoute,
  ContactsIdRoute: ContactsIdRoute,
  SelectionsDateRoute: SelectionsDateRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  SelectionsIndexRoute: SelectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
